apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: 0a580067.nip.io
    http:
      paths:
      - backend:
          service:
            name: podinfo
            port:
              number: 80
        path: /
        pathType: Prefix